[package]
# Your app's name
name = "dpedal_pcb"
# The current version; make sure to keep this up to date!
version = "0.0.1"
# The URL to the git repository; this is used for publishing releases
repository = "https://github.com/rukai/dpedal"
# The executables produced by your app
binaries = ["dpedal_gerber_files.zip"]
# The build command dist runs to produce those binaries
build-command = ["../export_pcb.sh"]