[workspace]
members = [
    "cargo:."
]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.2"
# CI backends to support
ci = "github"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["config.kdl"]
# The installers to generate for each app
installers = []
# Which actions to run on pull requests
pr-run-mode = "plan"
# Skip checking whether the specified configuration files are up to date
allow-dirty = []
# Checksums to generate for each App
checksum = "false"
# Generate and dist a source tarball
source-tarball = false

[[dist.extra-artifacts]]
artifacts = ["dpedal_gerber_files.zip"]
build = ["./compile_uf2.sh"]

[[dist.extra-artifacts]]
artifacts = ["dpedal_firmware.uf2"]
build = ["bash", "-c", "./install_kicad_ubuntu.sh; ./export_pcb.sh"]

# MANUAL STEP: Need to export these after creating the release and then reupload the zip
[[dist.extra-artifacts]]
artifacts = ["dpedal_3d_printed_parts.zip"]
build = ["zip", "dpedal_3d_printed_parts.zip", "readme.md"]
