[workspace]
members = [
    "cargo:.",
    "dist:pcb"
]

# Config for 'dist'
[dist]
display-name = "DPedal"
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.2"
# CI backends to support
ci = "github"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["config.kdl"]
# The installers to generate for each app
installers = []
# Which actions to run on pull requests
pr-run-mode = "plan"
# Skip checking whether the specified configuration files are up to date
allow-dirty = []
checksum = "false"
source-tarball = false

[[dist.extra-artifacts]]
artifacts = ["pcb/dpedal_gerber_files.zip"]
build = ["./export_pcb.sh"]

# MANUAL STEP: Need to export these after creating the release and then reupload the zip
[[dist.extra-artifacts]]
artifacts = ["dpedal_3d_printed_parts.zip"]
build = ["zip", "dpedal_3d_printed_parts.zip", "readme.md"]
